---
- name: Disable Root Login over SSH
  hosts: ubuntu-servers
  become: true

  tasks:
    - name: Set PermitRootLogin to 'no' in sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted
