---
- name: Disable Password-Based SSH Authentication
  hosts: ubuntu-servers
  become: true

  tasks:
    - name: Set PasswordAuthentication to 'no' in sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Restart SSH

    - name: Delete 50-cloud-init.conf that enabled PasswordAuthentication
      ansible.builtin.file:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf
        state: absent
  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted
